{
   'targets':[
        {
            'target_name':'an',
            'type':'<(library)',
            'dependencies':[],
            'defines':[],
            'include_dirs':[],
            'sources':[
                'main.cpp',
            ],
            'conditions':[]
        }
    ],
}
